node {

 notify('Started')

 try {

 // Get Artifactory server instance, defined in the Artifactory Plugin administration page.
    def server = Artifactory.server "artifactory-server-id"
    def buildInfo = Artifactory.newBuildInfo() 

 // Project Dir
    def project_path = "Download"


 stage('GitCheckOut') {
  git branch: 'Staging', credentialsId: '01', url: 'https://github.com/KRams2019/Devops-301.git'
 }


 dir(project_path){

 stage('Build Managment') {
      def downloadSpec = """{
	 "files": [
	{
	"pattern": "petclinic-war/*.war",
	"target": "files/"
        }
	]
	}"""
	server.download spec: downloadSpec
   }
	 
  stage('Deployment - Staging') {
      sh 'docker-compose up -d --build'
    }

 }

   notify('Completed')
 } catch(err){
   notify("Error ${err}")
   currentBuild.result = 'FAILURE'
  }
}

def notify(status){
   
}
