node {

  stage('GitCheckOut') {
   git branch: 'pre-production', url:'https://github.com/KRams2019/Devops-301.git'
 }

 def project_path = ""

 dir(project_path){

  stage('Maven Clean') {
   sh 'mvn clean'
  }

 stage('Maven Compile') {
  sh 'mvn compile'
 }

 stage('Maven test') {
  sh 'mvn test'
 }

 stage('Maven pkg') {
  sh 'mvn package'
 }

 stage('Archive Artifacts') {
  archive 'target/*.war'    
 }
}

stage('Tomcat Deployment'){
 deploy adapters: [tomcat8(credentialsId: 'deployer-tomcat', path: '', url: 'http://rlzvt92632dns.eastus2.cloudapp.azure.com:8080/')], contextPath: 'petclinic', onFailure: false, war: 'target/petclinic.war'
 }
 
}
