node {

  stage('GitCheckOut') {
   git branch: 'Pre-Production', url:'https://github.com/KRams2019/Devops-301.git'
 }

 def project_path = ""
 def server = Artifactory.server "artifactory-server-id"
 def buildInfo = Artifactory.newBuildInfo() 
 
 dir(project_path){

  stage('Maven Clean') {
   sh 'mvn clean'
  }

 stage('Maven Compile') {
  sh 'mvn compile'
 }

 stage('Maven test') {
  sh 'mvn test'
 }

 stage('Maven pkg') {
  sh 'mvn package'
 }

 stage('Build Managment') {
   def uploadSpec = """{
	  "files": [
	   {
	    "pattern": "**/*.war",
	     "target": "devops301-petclinic-war"
     }
	 ]
	 }"""
	   server.upload spec: uploadSpec
 }
}

stage('Tomcat Deployment'){
 deploy adapters: [tomcat8(credentialsId: 'deployer-tomcat', path: '', url: 'http://rlzvt92632dns.eastus2.cloudapp.azure.com:8080/')], contextPath: 'petclinic', onFailure: false, war: 'target/petclinic.war'
 }
 
}
